### PR TITLE
Generalize LE check

### PR DESCRIPTION
**Pull request by pkubaj**
Fixes build on FreeBSD/powerpc64le.

### CODE REVIEW

**Comment by SokoloffA** [comment]
Thank you for your interest in the project. 

I was surprised that there is no standard way to determine the endian.  
I can merge your PR without problem, but `__BYTE_ORDER__` is a gcc extension, maybe it's better to use [TestBigEndian](https://cmake.org/cmake/help/v3.5/module/TestBigEndian.html) from Cmake? What do you think?

**Comment by pkubaj** [comment]
FreeBSD uses clang, so clang also seems to use this extension.

If you prefer something else, clang also defines `__LITTLE_ENDIAN__`.

**Comment by SokoloffA** [comment]
By the way, do you know the bigendian architecture supported by qemu? For tests.

**Comment by pkubaj** [comment]
You could use e.g. ppc64 (big-endian 64-bit POWER).

**Comment by SokoloffA** [comment]
Thanks!

**Pull request merged**
